export let issue = [
  [
    "First start take more than one minute, and modify one file take 10s to recompile. Is this ok?",
  ],
  ["set webpack-uglify-plugin ecma support based on browserlist"],
  ["Misleading messages about script command changes when ejecting"],
  ["Code splitting and preventing duplication"],
  ["Proposal: explicit named imports for non-JS/CSS assets"],
  ["Inform user they've specified a HOST"],
  ['Add "debug-test" script by default'],
  ["Rest properties are broken with Jest + node v6"],
  ["'Npm start' fails on react-scripts-start initial attempt"],
  ["ERROR calling Images from public folder"],
  ["Documentation for NODE_PATH environment variable"],
  ["Can't use NODE_PATH with two directories"],
  ["Preparing the next release"],
  ["Invalidate cache by service worker"],
  ["Add WebWorker Support"],
  ["Re-compile loop while starting dev server"],
  ["CSS Loading Issue in development"],
  ["Make it clearer in error overlay when error boundary has caught an error"],
  ["Service worker fails to load new dynamic/code-split chunk"],
  ['Debugging in Chrome and FireFox not evaluating "let" and "const" vars'],
  ["Disable no-mixed-operators rule"],
  ["Asset paths in CSS"],
  ["[Question] Killing Process on Localhost with Cygwin"],
  ["Problem with new builds"],
  ["Symlink behaviour"],
];
